#**GridSearchCV and RandomSearchCV**

Taking Boston house price dataset to check accuracy of Random Forest Regression model and tuning hyperparameters-number of estimators and max depth of the tree to find the best value. 

First load boston data and split into train and test sets.

In [1]:
import numpy as np 
import pandas as pd


In [2]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
#raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [3]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [4]:
raw_df.iloc[::2, :]

0     1      2    3      4      5     6       7    8      9     10
0     0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3
2     0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8
4     0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8
6     0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7
8     0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7
...       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...
1002  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0
1004  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0
1006  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0
1008  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0
1010  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0

[506 rows x 11 columns]

In [5]:
raw_df.values[::2, :]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.0000e+00, 2.9600e+02,
        1.5300e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 2.0000e+00, 2.4200e+02,
        1.7800e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 2.0000e+00, 2.4200e+02,
        1.7800e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 1.0000e+00, 2.7300e+02,
        2.1000e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 1.0000e+00, 2.7300e+02,
        2.1000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 1.0000e+00, 2.7300e+02,
        2.1000e+01]])

In [6]:
raw_df.values[1::2, :2]

array([[396.9 ,   4.98],
       [396.9 ,   9.14],
       [392.83,   4.03],
       ...,
       [396.9 ,   5.64],
       [393.45,   6.48],
       [396.9 ,   7.88]])

In [7]:
data


array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [8]:
target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [9]:
#splitting data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data,target,test_size=0.3)

Apply Random Forest Regressor model with n_estimators of 5 and max_depth of 3

In [10]:
from sklearn import ensemble
dt=ensemble.RandomForestRegressor(n_estimators=5,max_depth=3)
dt.fit(x_train,y_train)
print('training score: ', dt.score(x_train,y_train))
print('test score: ',dt.score(x_test,y_test))

training score:  0.8788366333577137
test score:  0.8242751424754075


Let's try with cross validation and see:

In [11]:
from sklearn.model_selection import cross_val_score
scores1 = cross_val_score(ensemble.RandomForestRegressor(n_estimators=5,max_depth=3),x_train,y_train,cv=10)
np.average(scores1)

0.7712792344880324

The *Cross Validation* alone is not giving us something good. Let's combine it with *GridSearchCV*

For this, a list of dictionaries of the list of hyperparameter values is passed. Then model is evaluated on every combination of each list of values to find the best one.



In [12]:
ensemble.RandomForestRegressor().get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [13]:
model=ensemble.RandomForestRegressor()
from sklearn.model_selection import GridSearchCV

             
parameters={'n_estimators':[20,30,40,60,100], 'max_depth': 
             [5,10,15,20],'max_features':[2,5,8]}

grid_search = GridSearchCV(estimator=model,
                           param_grid=parameters,
                           cv=10,
                           n_jobs=-1)
                           
grid = grid_search.fit(x_train,y_train)
grid.best_score_

0.8724498066476803

In [14]:
grid.best_params_

{'max_depth': 10, 'max_features': 5, 'n_estimators': 100}

In [15]:
#trying the best hyperparameters suggested by GridSearchCV
#{'max_depth': 10, 'max_features': 5, 'n_estimators': 100}

from sklearn import ensemble
dt_1=ensemble.RandomForestRegressor(n_estimators=100, max_depth=10, max_features = 5)
dt_1.fit(x_train,y_train)
print('training score: ', dt_1.score(x_train,y_train))
print('test score: ',dt_1.score(x_test,y_test))

training score:  0.9789241164994994
test score:  0.8648407705399134


#Random Search CV

In Random search CV, the best combination can not be identified because all the combinations are not tested. But the advantage is we can test a broad range of values for hyperparameters within the same computation time as grid search CV.

Below is the implementation of Random search for the above example of Boston Housing prices dataset.

In [21]:
from sklearn.model_selection import RandomizedSearchCV
model=ensemble.RandomForestRegressor()
param_grid=[{'n_estimators':[20,30,40,60,100], 'max_depth':[5,10,15,20]
             ,'max_features':[2,5,8]}]

rnd_search = RandomizedSearchCV(model, param_grid, cv=10, 
                                          return_train_score=True)
rnd_search.fit(x_train,y_train)
rnd_search.best_score_

0.8739449171500796

In [22]:
rnd_search.best_params_

{'n_estimators': 100, 'max_features': 5, 'max_depth': 20}

In [23]:
#trying the best hyperparameters suggested by RandomizedSearchCV

#{'max_depth': 20, 'max_features': 5, 'n_estimators': 100}



from sklearn import ensemble
dt=ensemble.RandomForestRegressor(n_estimators=100, max_depth=20, max_features = 5)
dt.fit(x_train,y_train)
print('training score: ', dt.score(x_train,y_train))
print('test score: ',dt.score(x_test,y_test))

training score:  0.9830426012690847
test score:  0.8762320094346917


# **Save and Load Machine Learning Models**

In Machine Learning, when we finally arrive at the model that we are satisfied with, we can save and reuse it later.

In this session, we will see the two(2) most common ways of saving our model and reloading it for future predictions:

1. Finalize Your Model with pickle
2. Finalize Your Model with Joblib

#Finalize Your Model with pickle

Pickle is the standard way of serializing objects in Python. You can use the pickle1 operation to serialize your machine learning algorithms and save the serialized format to a file. Later you can load this file to deserialize your model and use it to make new predictions. The example below demonstrates how you can save your model to file and load it to make predictions on the unseen test set. We will save the best model from our previous tutorial(see code above).

In [24]:
import pickle


pickle.dump(dt_1, open('model.pkl', 'wb'))


In [25]:
# some time later...
# load the model from disk
pickled_model = pickle.load(open('model.pkl', 'rb'))

Running the example saves the model to finalized model.pkl in your local working directory. Load the saved model and evaluating it provides an estimate of accuracy of the model on unseen data.

In [28]:
y_pred=pickled_model.predict(x_test) 
y_pred

array([19.86319398, 29.03479874, 21.67350006, 12.71204121, 34.22842949,
       11.40221353, 14.66001471, 21.29399503, 13.4719047 , 22.85981053,
       17.36048343, 21.41748046, 17.01335   , 18.62380602, 22.5755202 ,
       19.15924998, 27.41328425, 39.58573504, 31.70050622, 23.72487966,
       41.61616667, 15.82841999, 16.37848333, 21.29667659, 25.95727204,
       10.93405498, 30.4089506 , 23.24675986, 19.69395124, 25.37527351,
       14.81242316, 24.10072915, 32.27576031, 37.61872222, 23.10131681,
       23.11682538, 21.40721619, 25.12841619, 22.09484811, 16.75098214,
       19.91458626, 19.27617484, 19.35961543, 26.81140713, 24.10948339,
       20.6659806 , 16.91375   , 22.21765414, 20.62331451, 22.17656163,
       33.99076537, 39.09634615, 35.74933651, 19.94217578, 16.08256074,
       24.3633496 , 18.64948639, 21.88880636, 42.13395833, 21.31239609,
       21.24798009, 25.57311403, 21.71417473, 19.45780084, 14.65615659,
       33.01102632, 16.68216339, 25.15535195, 21.44444813, 14.74

In [29]:
print('test score: ',pickled_model.score(x_test,y_test))

test score:  0.8648407705399134


#Finalize Your Model with Joblib

In [30]:
!pip install joblib

In [31]:
import joblib


joblib.dump(dt_1 , 'joblib_model')

['joblib_model']

In [33]:
jobLib = joblib.load('joblib_model')


In [34]:
y_pred_joblib=jobLib.predict(x_test)
y_pred_joblib

array([19.86319398, 29.03479874, 21.67350006, 12.71204121, 34.22842949,
       11.40221353, 14.66001471, 21.29399503, 13.4719047 , 22.85981053,
       17.36048343, 21.41748046, 17.01335   , 18.62380602, 22.5755202 ,
       19.15924998, 27.41328425, 39.58573504, 31.70050622, 23.72487966,
       41.61616667, 15.82841999, 16.37848333, 21.29667659, 25.95727204,
       10.93405498, 30.4089506 , 23.24675986, 19.69395124, 25.37527351,
       14.81242316, 24.10072915, 32.27576031, 37.61872222, 23.10131681,
       23.11682538, 21.40721619, 25.12841619, 22.09484811, 16.75098214,
       19.91458626, 19.27617484, 19.35961543, 26.81140713, 24.10948339,
       20.6659806 , 16.91375   , 22.21765414, 20.62331451, 22.17656163,
       33.99076537, 39.09634615, 35.74933651, 19.94217578, 16.08256074,
       24.3633496 , 18.64948639, 21.88880636, 42.13395833, 21.31239609,
       21.24798009, 25.57311403, 21.71417473, 19.45780084, 14.65615659,
       33.01102632, 16.68216339, 25.15535195, 21.44444813, 14.74

In [35]:
print('test score: ',jobLib.score(x_test,y_test))

test score:  0.8648407705399134
